### ISSUE TITLE
Can't add/remove apps to be tracked

### ISSUE THREAD

**Issue by MarlonDevio** [wakatime/macos-wakatime#193]
I can only select the following 4 apps to be tracked/or not tracked:

<img width="437" alt="Scherm­afbeelding 2024-01-02 om 15 48 16" src="https://github.com/wakatime/macos-wakatime/assets/108157984/4219e11f-96bd-48a1-9fd4-539933ce592b">

Is that normal behaviour?

I would love to select more apps that it would track and also exclude certain items like maybe webpages?

**Comment by alanhamlett** [comment]
That's normal, because it only displays apps with their [bundleId](https://developer.apple.com/documentation/appstoreconnectapi/bundle_ids) listed in [MonitoredApps](https://github.com/wakatime/macos-wakatime/blob/4ba6eab917ec2a555a06db5e41ab8b1e67ae2fae/WakaTime/Extensions/NSRunningApplicationExtension.swift#L3).

When tracking browsing, we should have the ability to exclude or include domains/urls by regex. I've added #196 to track this feature request.
