### ISSUE TITLE
Improve Zoom entity detection

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/macos-wakatime#228]
Currently it's detecting Zoom meetings as the window title, one of these:

* `zoom floating video window`
* `Zoom Meeting`
* `share screen window`
* `Zoom`

The meeting title was `WakaTime debug session`, which was never captured from the window title. We can use the new a11y method to find the meeting title from Zoom's a11y dom.

**Comment by starbugs** [comment]
The meeting title (if set) is only shown in the Zoom UI when you click the green icon on the upper left side of the meeting window. Otherwise, it's not part of the AX tree of the meeting window. But it is shown in the scheduled meeting sidebar of the Zoom main window - if that is not closed. I could try extracting the meeting title from there and match it to the current time and open zoom meeting window, but I am not sure how reliable that might be.

What might be possible is extracting the names of the participants from the AX tree of the meeting window. But I don't know if that was what you had in mind. Let me know how to proceed.

**Comment by alanhamlett** [comment]
> I could try extracting the meeting title from there and match it to the current time and open zoom meeting window, but I am not sure how reliable that might be.

No, it's not worth it. Let's skip this for now unless something changes in the Zoom app to make detecting meeting title easier.
